# Generated by Django 2.0.4 on 2019-10-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-created']},
        ),
    ]
