# Generated by Django 2.1.1 on 2019-10-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos_app', '0002_auto_20191024_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(),
        ),
    ]
