# Generated by Django 2.1.1 on 2019-10-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos_app', '0003_auto_20191025_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
